# Generated by Django 5.0.4 on 2024-05-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='dob',
        ),
    ]
