# Generated by Django 5.0.4 on 2024-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0003_signup1_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_flat_space', models.CharField(max_length=50)),
                ('parking_available', models.CharField(max_length=50)),
                ('payment_process', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
