# Generated by Django 5.0.4 on 2024-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0004_adminadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadd',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='adminadd',
            name='payment_process',
            field=models.CharField(max_length=55),
        ),
    ]
