# Generated by Django 5.0.4 on 2024-05-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0005_alter_adminadd_image_alter_adminadd_payment_process'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminadd',
            new_name='adminadd11',
        ),
    ]
