# Generated by Django 5.0.4 on 2024-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0006_rename_adminadd_adminadd11'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_flat_space', models.CharField(max_length=55)),
                ('floor_no', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('parking_available', models.CharField(max_length=55)),
                ('payment_process', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='adminadd11',
        ),
    ]
