# Generated by Django 5.0.4 on 2024-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0008_rename_total_flat_space_adminadd_totalflatspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tspace', models.CharField(max_length=55)),
                ('fno', models.CharField(max_length=55)),
                ('nrooms', models.CharField(max_length=55)),
                ('pslot', models.CharField(max_length=55)),
                ('pay', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
