# Generated by Django 5.0.4 on 2024-05-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0009_admindata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='tspace',
            new_name='tflat',
        ),
    ]
