# Generated by Django 5.0.4 on 2024-05-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0010_rename_tspace_admindata_tflat'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fno', models.CharField(max_length=55)),
                ('nrooms', models.CharField(max_length=55)),
                ('pslot', models.CharField(max_length=55)),
                ('pay', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
