# Generated by Django 5.0.4 on 2024-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0011_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=55)),
                ('t2', models.CharField(max_length=55)),
                ('t3', models.CharField(max_length=55)),
                ('t4', models.CharField(max_length=55)),
                ('t5', models.CharField(max_length=55)),
                ('t6', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='adminadd',
        ),
        migrations.DeleteModel(
            name='admindata',
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
