# Generated by Django 5.0.4 on 2024-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0012_sdata_delete_adminadd_delete_admindata_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t7', models.CharField(max_length=60)),
                ('t8', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
