# Generated by Django 5.0.4 on 2024-05-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0013_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='t8',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='t7',
            new_name='name',
        ),
    ]
