# Generated by Django 5.0.4 on 2024-05-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0014_rename_t8_image_image_rename_t7_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='image1',
        ),
    ]
