# Generated by Django 5.0.4 on 2024-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0016_rename_image_image1_uimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='villaimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
