# Generated by Django 5.0.4 on 2024-05-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0017_villaimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image1',
        ),
        migrations.AlterField(
            model_name='sdata',
            name='t6',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
