# Generated by Django 5.0.4 on 2024-05-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villapp', '0018_delete_image1_alter_sdata_t6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BED', models.CharField(max_length=50)),
                ('BATH', models.CharField(max_length=50)),
                ('ARE', models.CharField(max_length=50)),
                ('FLO', models.CharField(max_length=50)),
                ('PAR', models.CharField(max_length=50)),
                ('IMG', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
